// <auto-generated/>
#pragma warning disable CS0618
using Aevatar.HomeAssistantClient.Logbook.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Aevatar.HomeAssistantClient.Logbook
{
    /// <summary>
    /// Builds and executes requests for operations under \logbook
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LogbookRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Aevatar.HomeAssistantClient.logbook.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Aevatar.HomeAssistantClient.Logbook.Item.WithTimestampItemRequestBuilder"/></returns>
        public global::Aevatar.HomeAssistantClient.Logbook.Item.WithTimestampItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("timestamp", position);
                return new global::Aevatar.HomeAssistantClient.Logbook.Item.WithTimestampItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Logbook.LogbookRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogbookRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/logbook", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Logbook.LogbookRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogbookRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/logbook", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
