// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Aevatar.HomeAssistantClient.Services
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Services_services_turn_on_fields_advanced_fields_fields : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The brightness property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_brightness? Brightness { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_brightness Brightness { get; set; }
#endif
        /// <summary>The brightness_step property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_brightness_step? BrightnessStep { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_brightness_step BrightnessStep { get; set; }
#endif
        /// <summary>The color_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_color_name? ColorName { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_color_name ColorName { get; set; }
#endif
        /// <summary>The color_temp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_color_temp? ColorTemp { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_color_temp ColorTemp { get; set; }
#endif
        /// <summary>The flash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_flash? Flash { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_flash Flash { get; set; }
#endif
        /// <summary>The hs_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_hs_color? HsColor { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_hs_color HsColor { get; set; }
#endif
        /// <summary>The profile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_profile? Profile { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_profile Profile { get; set; }
#endif
        /// <summary>The rgbw_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_rgbw_color? RgbwColor { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_rgbw_color RgbwColor { get; set; }
#endif
        /// <summary>The rgbww_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_rgbww_color? RgbwwColor { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_rgbww_color RgbwwColor { get; set; }
#endif
        /// <summary>The white property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_white? White { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_white White { get; set; }
#endif
        /// <summary>The xy_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_xy_color? XyColor { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_xy_color XyColor { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields"/> and sets the default values.
        /// </summary>
        public Services_services_turn_on_fields_advanced_fields_fields()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "brightness", n => { Brightness = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_brightness>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_brightness.CreateFromDiscriminatorValue); } },
                { "brightness_step", n => { BrightnessStep = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_brightness_step>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_brightness_step.CreateFromDiscriminatorValue); } },
                { "color_name", n => { ColorName = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_color_name>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_color_name.CreateFromDiscriminatorValue); } },
                { "color_temp", n => { ColorTemp = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_color_temp>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_color_temp.CreateFromDiscriminatorValue); } },
                { "flash", n => { Flash = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_flash>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_flash.CreateFromDiscriminatorValue); } },
                { "hs_color", n => { HsColor = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_hs_color>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_hs_color.CreateFromDiscriminatorValue); } },
                { "profile", n => { Profile = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_profile>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_profile.CreateFromDiscriminatorValue); } },
                { "rgbw_color", n => { RgbwColor = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_rgbw_color>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_rgbw_color.CreateFromDiscriminatorValue); } },
                { "rgbww_color", n => { RgbwwColor = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_rgbww_color>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_rgbww_color.CreateFromDiscriminatorValue); } },
                { "white", n => { White = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_white>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_white.CreateFromDiscriminatorValue); } },
                { "xy_color", n => { XyColor = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_xy_color>(global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_xy_color.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_brightness>("brightness", Brightness);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_brightness_step>("brightness_step", BrightnessStep);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_color_name>("color_name", ColorName);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_color_temp>("color_temp", ColorTemp);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_flash>("flash", Flash);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_hs_color>("hs_color", HsColor);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_profile>("profile", Profile);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_rgbw_color>("rgbw_color", RgbwColor);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_rgbww_color>("rgbww_color", RgbwwColor);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_white>("white", White);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_turn_on_fields_advanced_fields_fields_xy_color>("xy_color", XyColor);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
