// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Aevatar.HomeAssistantClient.Services
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Services_services_create_fields : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The entities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_entities? Entities { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_entities Entities { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_message? Message { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_message Message { get; set; }
#endif
        /// <summary>The notification_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_notification_id? NotificationId { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_notification_id NotificationId { get; set; }
#endif
        /// <summary>The scene_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_scene_id? SceneId { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_scene_id SceneId { get; set; }
#endif
        /// <summary>The snapshot_entities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_snapshot_entities? SnapshotEntities { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_snapshot_entities SnapshotEntities { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_title? Title { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_title Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields"/> and sets the default values.
        /// </summary>
        public Services_services_create_fields()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entities", n => { Entities = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_entities>(global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_entities.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_message>(global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_message.CreateFromDiscriminatorValue); } },
                { "notification_id", n => { NotificationId = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_notification_id>(global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_notification_id.CreateFromDiscriminatorValue); } },
                { "scene_id", n => { SceneId = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_scene_id>(global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_scene_id.CreateFromDiscriminatorValue); } },
                { "snapshot_entities", n => { SnapshotEntities = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_snapshot_entities>(global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_snapshot_entities.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_title>(global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_title.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_entities>("entities", Entities);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_message>("message", Message);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_notification_id>("notification_id", NotificationId);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_scene_id>("scene_id", SceneId);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_snapshot_entities>("snapshot_entities", SnapshotEntities);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_create_fields_title>("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
