// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Aevatar.HomeAssistantClient.Services
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Services_services_cloud_say_fields : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cache property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_cache? Cache { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_cache Cache { get; set; }
#endif
        /// <summary>The entity_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_entity_id? EntityId { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_entity_id EntityId { get; set; }
#endif
        /// <summary>The language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_language? Language { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_language Language { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_message? Message { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_message Message { get; set; }
#endif
        /// <summary>The options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_options? Options { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_options Options { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields"/> and sets the default values.
        /// </summary>
        public Services_services_cloud_say_fields()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cache", n => { Cache = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_cache>(global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_cache.CreateFromDiscriminatorValue); } },
                { "entity_id", n => { EntityId = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_entity_id>(global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_entity_id.CreateFromDiscriminatorValue); } },
                { "language", n => { Language = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_language>(global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_language.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_message>(global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_message.CreateFromDiscriminatorValue); } },
                { "options", n => { Options = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_options>(global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_options.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_cache>("cache", Cache);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_entity_id>("entity_id", EntityId);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_language>("language", Language);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_message>("message", Message);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_cloud_say_fields_options>("options", Options);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
