// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Aevatar.HomeAssistantClient.Services
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Services_services_purge_fields : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The apply_filter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_apply_filter? ApplyFilter { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_apply_filter ApplyFilter { get; set; }
#endif
        /// <summary>The keep_days property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_keep_days? KeepDays { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_keep_days KeepDays { get; set; }
#endif
        /// <summary>The repack property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_repack? Repack { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_repack Repack { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields"/> and sets the default values.
        /// </summary>
        public Services_services_purge_fields()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apply_filter", n => { ApplyFilter = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_apply_filter>(global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_apply_filter.CreateFromDiscriminatorValue); } },
                { "keep_days", n => { KeepDays = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_keep_days>(global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_keep_days.CreateFromDiscriminatorValue); } },
                { "repack", n => { Repack = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_repack>(global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_repack.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_apply_filter>("apply_filter", ApplyFilter);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_keep_days>("keep_days", KeepDays);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_purge_fields_repack>("repack", Repack);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
