// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Aevatar.HomeAssistantClient.Services
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Services_services_get_statistics_fields : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The end_time property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_end_time? EndTime { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_end_time EndTime { get; set; }
#endif
        /// <summary>The period property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_period? Period { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_period Period { get; set; }
#endif
        /// <summary>The start_time property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_start_time? StartTime { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_start_time StartTime { get; set; }
#endif
        /// <summary>The statistic_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_statistic_ids? StatisticIds { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_statistic_ids StatisticIds { get; set; }
#endif
        /// <summary>The types property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_types? Types { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_types Types { get; set; }
#endif
        /// <summary>The units property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_units? Units { get; set; }
#nullable restore
#else
        public global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_units Units { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields"/> and sets the default values.
        /// </summary>
        public Services_services_get_statistics_fields()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end_time", n => { EndTime = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_end_time>(global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_end_time.CreateFromDiscriminatorValue); } },
                { "period", n => { Period = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_period>(global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_period.CreateFromDiscriminatorValue); } },
                { "start_time", n => { StartTime = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_start_time>(global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_start_time.CreateFromDiscriminatorValue); } },
                { "statistic_ids", n => { StatisticIds = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_statistic_ids>(global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_statistic_ids.CreateFromDiscriminatorValue); } },
                { "types", n => { Types = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_types>(global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_types.CreateFromDiscriminatorValue); } },
                { "units", n => { Units = n.GetObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_units>(global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_units.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_end_time>("end_time", EndTime);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_period>("period", Period);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_start_time>("start_time", StartTime);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_statistic_ids>("statistic_ids", StatisticIds);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_types>("types", Types);
            writer.WriteObjectValue<global::Aevatar.HomeAssistantClient.Services.Services_services_get_statistics_fields_units>("units", Units);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
