namespace AISmartHome.Agents.Storage;

/// <summary>
/// Interface for embedding generation service
/// Converts text to vector representations for semantic search
/// </summary>
public interface IEmbeddingService
{
    /// <summary>
    /// Generate embedding for a single text
    /// </summary>
    Task<float[]> GenerateEmbeddingAsync(string text, CancellationToken ct = default);
    
    /// <summary>
    /// Generate embeddings for multiple texts (batch operation)
    /// </summary>
    Task<List<float[]>> GenerateEmbeddingsAsync(List<string> texts, CancellationToken ct = default);
    
    /// <summary>
    /// Get the dimensionality of embeddings generated by this service
    /// </summary>
    int EmbeddingDimension { get; }
}

