// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Aevatar.HomeAssistantClient.States.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithEntity_GetResponse_attributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The friendly_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyName { get; set; }
#nullable restore
#else
        public string FriendlyName { get; set; }
#endif
        /// <summary>The percentage property</summary>
        public int? Percentage { get; set; }
        /// <summary>The percentage_step property</summary>
        public double? PercentageStep { get; set; }
        /// <summary>The preset_mode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PresetMode { get; set; }
#nullable restore
#else
        public string PresetMode { get; set; }
#endif
        /// <summary>The preset_modes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PresetModes { get; set; }
#nullable restore
#else
        public List<string> PresetModes { get; set; }
#endif
        /// <summary>The supported_features property</summary>
        public int? SupportedFeatures { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.States.Item.WithEntity_GetResponse_attributes"/> and sets the default values.
        /// </summary>
        public WithEntity_GetResponse_attributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Aevatar.HomeAssistantClient.States.Item.WithEntity_GetResponse_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Aevatar.HomeAssistantClient.States.Item.WithEntity_GetResponse_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Aevatar.HomeAssistantClient.States.Item.WithEntity_GetResponse_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "friendly_name", n => { FriendlyName = n.GetStringValue(); } },
                { "percentage", n => { Percentage = n.GetIntValue(); } },
                { "percentage_step", n => { PercentageStep = n.GetDoubleValue(); } },
                { "preset_mode", n => { PresetMode = n.GetStringValue(); } },
                { "preset_modes", n => { PresetModes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "supported_features", n => { SupportedFeatures = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("friendly_name", FriendlyName);
            writer.WriteIntValue("percentage", Percentage);
            writer.WriteDoubleValue("percentage_step", PercentageStep);
            writer.WriteStringValue("preset_mode", PresetMode);
            writer.WriteCollectionOfPrimitiveValues<string>("preset_modes", PresetModes);
            writer.WriteIntValue("supported_features", SupportedFeatures);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
