// <auto-generated/>
#pragma warning disable CS0618
using Aevatar.HomeAssistantClient.Config.Core.Check_config;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Aevatar.HomeAssistantClient.Config.Core
{
    /// <summary>
    /// Builds and executes requests for operations under \config\core
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CoreRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The check_config property</summary>
        public global::Aevatar.HomeAssistantClient.Config.Core.Check_config.Check_configRequestBuilder Check_config
        {
            get => new global::Aevatar.HomeAssistantClient.Config.Core.Check_config.Check_configRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Config.Core.CoreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CoreRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/config/core", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Config.Core.CoreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CoreRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/config/core", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
