// <auto-generated/>
#pragma warning disable CS0618
using Aevatar.HomeAssistantClient.States.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Aevatar.HomeAssistantClient.States
{
    /// <summary>
    /// Builds and executes requests for operations under \states
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Aevatar.HomeAssistantClient.states.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Aevatar.HomeAssistantClient.States.Item.WithEntity_ItemRequestBuilder"/></returns>
        public global::Aevatar.HomeAssistantClient.States.Item.WithEntity_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("entity_id", position);
                return new global::Aevatar.HomeAssistantClient.States.Item.WithEntity_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.States.StatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/states", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.States.StatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/states", rawUrl)
        {
        }
        /// <summary>
        /// Returns an array of state objects. Each state has the following attributes: `entity_id`, `state`, `attributes`, `last_changed`, `last_reported`, `last_updated` and `context`.```[    {        &quot;entity_id&quot;: &quot;conversation.home_assistant&quot;,        &quot;state&quot;: &quot;unknown&quot;,        &quot;attributes&quot;: {            &quot;friendly_name&quot;: &quot;Home Assistant&quot;,            &quot;supported_features&quot;: 1        },        &quot;last_changed&quot;: &quot;2025-10-09T06:30:12.612675+00:00&quot;,        &quot;last_reported&quot;: &quot;2025-10-09T06:30:12.612675+00:00&quot;,        &quot;last_updated&quot;: &quot;2025-10-09T06:30:12.612675+00:00&quot;,        &quot;context&quot;: {            &quot;id&quot;: &quot;01K73TKDW4C48KG8A0NNXSRTC7&quot;,            &quot;parent_id&quot;: null,            &quot;user_id&quot;: null        }    },    {        &quot;entity_id&quot;: &quot;event.backup_automatic_backup&quot;,        &quot;state&quot;: &quot;unknown&quot;,        &quot;attributes&quot;: {            &quot;event_types&quot;: [                &quot;completed&quot;,                &quot;failed&quot;,                &quot;in_progress&quot;            ],            &quot;event_type&quot;: null,            &quot;friendly_name&quot;: &quot;Backup 自动备份&quot;        },        &quot;last_changed&quot;: &quot;2025-10-09T06:30:12.673966+00:00&quot;,        &quot;last_reported&quot;: &quot;2025-10-09T06:30:12.673966+00:00&quot;,        &quot;last_updated&quot;: &quot;2025-10-09T06:30:12.673966+00:00&quot;,        &quot;context&quot;: {            &quot;id&quot;: &quot;01K73TKDY17ANFF62GWK60GMS0&quot;,            &quot;parent_id&quot;: null,            &quot;user_id&quot;: null        }    }]```Sample `curl` command:```curl \  -H &quot;Authorization: Bearer TOKEN&quot; \  -H &quot;Content-Type: application/json&quot; http://localhost:8123/api/states```
        /// </summary>
        /// <returns>A List&lt;global::Aevatar.HomeAssistantClient.States.States&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Aevatar.HomeAssistantClient.States.States>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Aevatar.HomeAssistantClient.States.States>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Aevatar.HomeAssistantClient.States.States>(requestInfo, global::Aevatar.HomeAssistantClient.States.States.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Returns an array of state objects. Each state has the following attributes: `entity_id`, `state`, `attributes`, `last_changed`, `last_reported`, `last_updated` and `context`.```[    {        &quot;entity_id&quot;: &quot;conversation.home_assistant&quot;,        &quot;state&quot;: &quot;unknown&quot;,        &quot;attributes&quot;: {            &quot;friendly_name&quot;: &quot;Home Assistant&quot;,            &quot;supported_features&quot;: 1        },        &quot;last_changed&quot;: &quot;2025-10-09T06:30:12.612675+00:00&quot;,        &quot;last_reported&quot;: &quot;2025-10-09T06:30:12.612675+00:00&quot;,        &quot;last_updated&quot;: &quot;2025-10-09T06:30:12.612675+00:00&quot;,        &quot;context&quot;: {            &quot;id&quot;: &quot;01K73TKDW4C48KG8A0NNXSRTC7&quot;,            &quot;parent_id&quot;: null,            &quot;user_id&quot;: null        }    },    {        &quot;entity_id&quot;: &quot;event.backup_automatic_backup&quot;,        &quot;state&quot;: &quot;unknown&quot;,        &quot;attributes&quot;: {            &quot;event_types&quot;: [                &quot;completed&quot;,                &quot;failed&quot;,                &quot;in_progress&quot;            ],            &quot;event_type&quot;: null,            &quot;friendly_name&quot;: &quot;Backup 自动备份&quot;        },        &quot;last_changed&quot;: &quot;2025-10-09T06:30:12.673966+00:00&quot;,        &quot;last_reported&quot;: &quot;2025-10-09T06:30:12.673966+00:00&quot;,        &quot;last_updated&quot;: &quot;2025-10-09T06:30:12.673966+00:00&quot;,        &quot;context&quot;: {            &quot;id&quot;: &quot;01K73TKDY17ANFF62GWK60GMS0&quot;,            &quot;parent_id&quot;: null,            &quot;user_id&quot;: null        }    }]```Sample `curl` command:```curl \  -H &quot;Authorization: Bearer TOKEN&quot; \  -H &quot;Content-Type: application/json&quot; http://localhost:8123/api/states```
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Aevatar.HomeAssistantClient.States.StatesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Aevatar.HomeAssistantClient.States.StatesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Aevatar.HomeAssistantClient.States.StatesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StatesRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
