// <auto-generated/>
#pragma warning disable CS0618
using Aevatar.HomeAssistantClient.Camera_proxy.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Aevatar.HomeAssistantClient.Camera_proxy
{
    /// <summary>
    /// Builds and executes requests for operations under \camera_proxy
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Camera_proxyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Aevatar.HomeAssistantClient.camera_proxy.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Aevatar.HomeAssistantClient.Camera_proxy.Item.WithCarera_entity_ItemRequestBuilder"/></returns>
        public global::Aevatar.HomeAssistantClient.Camera_proxy.Item.WithCarera_entity_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("carera_entity_id", position);
                return new global::Aevatar.HomeAssistantClient.Camera_proxy.Item.WithCarera_entity_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Camera_proxy.Camera_proxyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Camera_proxyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/camera_proxy", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Camera_proxy.Camera_proxyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Camera_proxyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/camera_proxy", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
