// <auto-generated/>
#pragma warning disable CS0618
using Aevatar.HomeAssistantClient.Intent.Handle;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Aevatar.HomeAssistantClient.Intent
{
    /// <summary>
    /// Builds and executes requests for operations under \intent
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IntentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The handle property</summary>
        public global::Aevatar.HomeAssistantClient.Intent.Handle.HandleRequestBuilder Handle
        {
            get => new global::Aevatar.HomeAssistantClient.Intent.Handle.HandleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Intent.IntentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/intent", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Aevatar.HomeAssistantClient.Intent.IntentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/intent", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
